/*
 * @copyright   Copyright (C) 2022 AesirX. All rights reserved.
 * @license     GNU General Public License version 3, see LICENSE.
 */

export const WEBSOCKET_EVENT_SIGNATURES = {
  CPN_JOINING_ROOM: 'JOINING_ROOM',

  CPN_ON_WEBSOCKET_ERROR: 'connect_error',

  PUSH_CALLBACK_CHANNEL: 'PUSH_CALLBACK_CHANNEL',
  FORWARD_CALLBACK_CHANNEL: 'FORWARD_CALLBACK_CHANNEL',
  ON_FORCE_TO_CLOSE_CONNECTION: 'FORCE_TO_CLOSE_CONNECTION',
};
